version: '3.8'
services:
  postgres:
    image: postgres:14.2
    ports:
      - "54345:5432"
    volumes:
      - type: bind
        source: ./DockerData/postgresql/data
        target: /var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: earful-obtain-estranged-whiny-enjoyer-graceful
